### ISSUE TITLE
Auth token issue

### ISSUE THREAD

**Issue by sprathod369** [akto-api-security/akto#1336]
1) Set up the latest version 1.42.5 using docker compose setup on-prem. I am running Akto locally.
2) Upload my test postman collection and run test selecting all available tests - no test role selected (default). However, the button to trigger tests is disabled as it flags and issue that no auth token set. This was not an issue in earlier version where same postman collection file was used that had the bearer token.
3) Tried creating a user and configured auth for the user.
4) Now the Run test button to trigger all test was enabled but no issues or finding were reported after the test execution.

It is a bit frustrating as documention and guides have no information on user and authentication related nuances and it seems every version released have more serious bugs that are showstopper in adopting the opensource version of Akto.

Any support will be appreciated

**Comment by avneesh-akto** [comment]
Hi @sprathod369. Sorry you faced issue while running tests with Akto. 

Akto needs an attacker token (different from the one you have in your Postman collection) to run tests. Follow this doc link to setup attacker token: https://docs.akto.io/api-security-testing/concepts/user-config#id-1.-configure-attacker-token

Can you send me the screenshot of your tests page. The test results page has multiple tabs (check attached image) where we show the attempts Akto made. There are 4 tabs:


1. **Vulnerable**: Here all your vulnerable APIs will show up.
2. **Needs configuration**: All the tests that couldn't be initiated due to missing configuration. If Akto finds such tests it will also mention what configuration you need to add to run the tests (attached screenshot).
3. **Skipped**: This tab has the tests that Akto couldn't run because it didn't match the conditions required for a test to run. For example if a test has the condition to run only on APIs with status code == 200, then it will skip APIs with non 200 response codes.
4. **No vulnerability found**: This tab has the all the tests that were successfully run but Akto couldn't find vulnerabilities in them. 

I hope this clears the confusion. If you need further help do ping us on support@akto.io


<img width="1166" alt="image" src="https://github.com/user-attachments/assets/58977576-f3a4-4bf1-aa63-cf4098355062">

**Comment by sprathod369** [comment]
Thanks for the response @avneesh-akto . Seems the newer versions released need this role configuration. The earlier versions I tested and played around did not require this as it just worked out of the box with default role. 
I'll close this out if that's the case. On a side note, I keep moving to a newer version after every release and get blocked with something new or unexpected result outcomes that are different from earlier version for the same set of collection.
At times is is very frustrating and makes me wonder if Akto really wants folks to use on-prem opensource version with whatever limited working features it provides or actually wants folks to move to the paid versions of Akto. 
Thanks again for your support.
