### ISSUE TITLE
Using BurpSuite extensions

### ISSUE THREAD

**Issue by B1gM8c** [akto-api-security/akto#291]
The first time I installed the plugin, I was able to retrieve the URL normally. Afterwards, I upgraded to the latest version of this project, deleted the old Docker images, and restarted it. Then I clicked to download the BurpSuite extension Akto.jar and loaded it into the extensions. However, when I tried to use it again, an error message popped up saying "Invalid API Key", and there were also error logs.
```
Error in sending health checkup: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403 Forbidden</h2>
<table>
<tr><th>URI:</th><td>/api/uploadHar</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>Forbidden</td></tr>
<tr><th>SERVLET:</th><td>default</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.51.v20230217</a><hr/>

</body>
</html>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403 Forbidden</h2>
<table>
<tr><th>URI:</th><td>/api/uploadHar</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>Forbidden</td></tr>
<tr><th>SERVLET:</th><td>default</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.51.v20230217</a><hr/>

</body>
</html>
```

**Comment by avneesh-akto** [comment]
Hello @B1gM8c . Thank you for trying out Akto.

This is because when you downloaded the burp plugin first time, it came with it's own API key. Since you reinstalled Akto the older API key got deleted. 

You have 2 ways to fix this:

1. a. Re-download the Burp plugin
    b. Remove the old plugin and load the current one.
 
2. a. Open akto. Go to Settings > Integrations > Burp Suite
    b. Generate a new API key.
    c. Open akto plugin in burp. Click on "Options".
    d. Paste the API key in "Akto token" field (image below)
    
    
<img width="784" alt="image" src="https://user-images.githubusercontent.com/91518451/233678175-1e9701a0-226b-49e6-b212-1081b55cbd02.png">

This should fix your issue. But if issue persists or you have further questions. Feel free to join our [discord](https://discord.com/invite/Wpc6xVME4s)
