### ISSUE TITLE
No Paths imported from Postman Collection

### ISSUE THREAD

**Issue by Alucard23890** [akto-api-security/akto#424]
Hi,
I tried to import a Postman Collection generated from the OWASP Benchmark OpenAPI specification into Akto. Ako added an entry to the API Inventory, but no endpoints were added. I don't have any errors while importing the collection. Importing the collection via API Key or reducing the collection size did not work either. Did I do something wrong? 

You will find the collection attached.

Thanks in Advance.
[OWASP Benchmark Test Application.postman_collection.json.txt](https://github.com/akto-api-security/akto/files/11995885/OWASP.Benchmark.Test.Application.postman_collection.json.txt)

**Comment by ankush-jain-akto** [comment]
Hi @Alucard23890 - will check this and get back to you.

**Comment by hknclk** [comment]
I've same issue with a custom Postman project. It seems like Akto creates the collection successfully however can't add any urls under it. Using Postman v2.1 collection as suggested in the document.

**Comment by avneesh-akto** [comment]
Hi @hknclk 

If your Postman collection doesn't have responses Akto will hit those APIs to generate responses.
Since the collections are being created but no endpoints are being shown, can you please confirm if those APIs are accessible from Akto dashboard server.

Reasons why it is not accessible:

1. APIs are internal
2. Akto dashboard server has no internet connection

**Comment by avneesh-akto** [comment]
Hi @Alucard23890 

I've reviewed your Postman collection and noticed that all the endpoints are returning 5xx status codes. However, Akto, only processes APIs that return 2xx response codes. It would be great if you could update the endpoints to return the appropriate 2xx response codes so that Akto can process them correctly.

**Comment by Alucard23890** [comment]
Hi @avneesh-akto 
Thank you for your review. I could import my collection with your tips. What seems to be an error: On the API Inventory page, I can see the total number of 2740 Endpoints for this collection, but when I open the collection, there are "only" 2000 Endpoints. Is there a limit in Akto?

Thanks again.

**Comment by avneesh-akto** [comment]
You are correct, @Alucard23890. Currently, there is a limitation of 2000 endpoints for postman collection. However, we are actively engaged in refining our system to eliminate this restriction.

**Comment by avneesh-akto** [comment]
Closing this issue. If you encounter any further problems or have any other concerns, please don't hesitate to reach out to us on our [Discord](https://discord.com/invite/Wpc6xVME4s) channel. We're here to help!
