### ISSUE TITLE
port 9090 issue

### ISSUE THREAD

**Issue by Digita1ocean** [akto-api-security/akto#610]
I want to be able to open port 9090 after the Docker is running, but im unable to do so.port 8080 is opening but not localhost on port 9090.

**Comment by ankush-jain-akto** [comment]
Hi @Digita1ocean - if I understand correctly, you want to start Akto on port 8080 instead of the default 9090 port?

You can modify `docker-compose.yml` [here](https://github.com/akto-api-security/akto/blob/master/docker-compose.yml). - on line 19, change `9090:8080` to `8080:8080` 
- docker-compose down && docker-compose up -d

**Comment by ankush-jain-akto** [comment]
Hi @Digita1ocean - did this help? Please let us know.
